apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
data:
  PORT: "3000"
  NODE_ENV: "production"
  SERVICE_NAME: "order-service"
  DB_HOST: "host.docker.internal"
  DB_USER: "root"
  DB_NAME: "order_db"
  KAFKA_BROKER: "kafka:9092"