version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  gateway-service:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "3000:3000"

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    ports:
      - "3001:3000"

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "3002:3000"

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    ports:
      - "3003:3000"
    environment:
      KAFKA_BROKER: kafka:9092

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    ports:
      - "3004:3000"
    environment:
      KAFKA_BROKER: kafka:9092

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    ports:
      - "3005:3000"
    environment:
      KAFKA_BROKER: kafka:9092