apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
data:
  PORT: "3000"
  NODE_ENV: "production"
  SERVICE_NAME: "notification-service"
  DB_HOST: "host.docker.internal"
  DB_USER: "root"
  DB_NAME: "notification_db"
  KAFKA_BROKER: "kafka:9092"
  EMAIL_USER: "pawarsatish8292@gmail.com"